name: CI

on:
    push:
        branches: [main, develop]
    pull_request:
        branches: [main, develop]

permissions:
    actions: write
    attestations: write
    checks: write
    contents: write
    packages: write
    id-token: write
    security-events: write

jobs:
    ci:
        name: Continuous Integration
        uses: jdfalk/ghcommon/.github/workflows/reusable-ci.yml@378e23a96c00d719075732dd2af4de45f7523cbb # v1.10.4
        with:
            go-version: "1.24"
        secrets: inherit
