name: CI

on:
    push:
        branches: [main, develop]
    pull_request:
        branches: [main, develop]

permissions:
    actions: write
    attestations: write
    checks: write
    contents: write
    packages: write
    id-token: write
    security-events: write

jobs:
    ci:
        name: Continuous Integration
        uses: falkcorp/github-common/.github/workflows/reusable-ci.yml@d0c3326b96557c8ea9117c1c196b628e5e028186 # v1.10.8
        with:
            go-version: "1.26"
        secrets: inherit
